config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :robots do
    resources :bookings, only: [ :new, :create, :show ]
  end

  resources :bookings, only: [] do
    resources :reviews, only: [ :new, :create ]
  end

  get "/dashboard", to: "pages#dashboard"
  # resources :bookmarks, only: [ :new, :create, :destroy]
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :robot
  belongs_to :user
  has_many :reviews
  validates :activity, presence: true
  validates :comment, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  has_one :robot, through: :bookings
end

app/models/robot.rb
class Robot < ApplicationRecord
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :robots
         has_many :bookings
         has_many :reviews, through: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action  :authenticate_user!
  before_action  :configure_permitted_parameters, if: :devise_controller?

  def after_sign_up_path_for
    robots_path
  end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :define_robot, only: %i[new create show]
  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.robot = @robot
    @booking.user = current_user
    # @booking.robot[id] = @robot[id]


    if @booking.save
      #redirect_to robot_booking_path(@booking.robot_id, @booking), notice: 'You successfully booked a robot!'
      redirect_to new_robot_booking_path(@robot), notice: "You successfully booked this robot!"
    else
      render :new
    end
  end

  def show

  end

  private

  def booking_params
    # strong params
    params.require(:booking).permit(:comment, :activity)
  end

  def define_robot
    @robot = Robot.find(params[:robot_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

  def dashboard
    @user_bookings = current_user.bookings
    @user_robots = current_user.robots
    @user_venue = @user_b
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :define_booking, only: [ :new, :create ]

  def new
    @review = Review.new
    @robot = @booking.robot
  end

  def create
    @review = Review.new(review_params)
    @review.booking_id = @booking.id
    @robot = @booking.robot
    if @review.save
      redirect_to robot_path(@robot)
    else
      render :new
    end
  end

  private

  def define_booking
    @booking = Booking.find(params[:booking_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/controllers/robots_controller.rb
class RobotsController < ApplicationController
  def index
    @robots = Robot.all
  end

  def show
    @robot = Robot.find(params[:id])
    @booking = Booking.find_by(robot: @robot)
  end

  def new
    @robot = Robot.new
  end

  def create
    @robot = Robot.new(robot_params)
    @user = current_user
    @robot.user_id = @user.id
    if @robot.save
      redirect_to dashboard_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def robot_params
    params.require(:robot).permit(:model, :overview, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="new-booking-container d-flex justify-content-center" data-controller="fake-modal">
  <div class="container m-4 p-4">
    <div class="row align-items-center row justify-content-center font-form">
      <div class="col-lg-7 m-3 p-4 rounded border coloring">
        <div class="d-flex justify-content-between align-items-center">
          <div>
            <h1>Robot specs</h1>
            <p>Model: <%= @robot.model %></p>
            <p>Overview: <%= @robot.overview %></p>
            <p>Price: <%= @robot.price %></p>
            <p>Rating: <%= @robot.rating %></p>
          </div>
          <div>
            <img class="img-properties-form" src="<%= @robot.image_urls.first %>" alt="Robot-picture">
          </div>
        </div>
      </div>

      <%# <div class="col-4 m-4 rounded border coloring dimension">
      </div> %>

      <% if flash[:notice] == 'You successfully booked this robot!' %>
        <div class="background hidden_success">
          <div class="modal_wrapper">
            <div class="booking">
              <div class="booking-info">
                <h1>Booking Details:</h1>
                <img src="<%= @robot.image_urls.first %>" style="height: 50%">
                <p><strong>Robot Model:</strong> <%= @robot.model %></p>
                <p></p>
                <p><%= notice %></p>
                <p><%= link_to 'Browse more Robots', robots_path, class: "btn btn-dark mb-3" %>            <%= link_to 'See my bookings', dashboard_path, class: "btn rounded border btn-light mb-3" %></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>

        <div class="col-lg-7 m-3 p-4 rounded border coloring">
          <h2> Book your bad boy here: </h2>
          <%= render "shared/form_booking", robot: @robot, booking: @booking%>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RobotRental</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Abril+Fatface&family=JetBrains+Mono:wght@500&family=Merriweather:ital@0;1&family=Open+Sans:wght@300&family=Work+Sans:wght@400;500;800&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/@splidejs/splide@4.1.4/dist/css/splide.min.css" rel="stylesheet">

  </head>

  <body>
    <%= render "shared/flashes" %>

    <% if params[:controller] == "pages" && params[:action] == "home"  %>
      <%= nil %>
      <% else %>
      <%= render "shared/navbar" %>
    <% end %>
    <%# <div class="container p-4"> %>
      <%= yield %>
    <%# </div> %>

  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container font-db">
  <div class="first-wrapper">
    <div class="style-db layout-db-1">
      <div class="d-flex align-items-center justify-content-between">
        <div>
        <div>
          <img class="icon-db mb-3" src="https://res.cloudinary.com/wagon/image/upload/c_fill,g_face,h_200,w_200/v1696521230/ovamdokvvff2re3cyxwk.jpg" alt="icon-user">
        </div>
          <h1>Your Info</h1>
            <% if user_signed_in? %>
            <p class="border-bottom p-2">First name: <%= current_user.first_name %></p>
            <p class="border-bottom p-2">Last name: <%= current_user.last_name %></p>
            <p class="border-bottom p-2">Email: <%= current_user.email %></p>
            <% end %>
            <a href="<%= dashboard_path %>" class="btn btn-dark text-white w-100 mt-2" style="text-decoration: none;">Edit profile</a>
        </div>
      </div>
    </div>

    <div class="style-db layout-db-1">
      <h1>Activity</h1>
        <%# add some counting mechanics %>
        <div class="activity-wrapper mt-5">
          <div class="style-activity-db">
            <h2>10</h2>
            <p>Active bookings</p>
          </div>
          <div class="style-activity-db">
            <h2>3</h2>
            <p>Robots owned</p>
          </div>
          <div class="style-activity-db">
            <h2 style="color: green">$0</h2>
            <p>Earned</p>
          </div>

          <div class="style-activity-db">
            <h2 style="color: darkred">$20</h2>
            <p>Spent</p>
          </div>
        </div>
    </div>
  </div>

  <div>
    <div class="style-db layout-db-2">
      <h1>Your Bookings</h1>
      <%= render "shared/table_bookings", user_bookings: @user_bookings %>

      <a href="<%= robots_path %>" class="btn btn-dark text-white mt-5" style="text-decoration: none;">
        + Book Another Robot
      </a>
    </div>

    <div class="style-db layout-db-2">
      <h1 class="mb-5">Your Robot Garage</h1>
      <%= render "shared/table_robots", user_robots: @user_robots %>


      <%# <div class="mb-0">
        <p class="border-bottom p-2">Atlas</p>
        <p class="border-bottom p-2">Spot</p>
        <p class="border-bottom p-2">C-3PO</p>
        <p class="border-bottom p-2">Terminator</p>
        <p class="border-bottom p-2">Robocop</p>
      </div> %>
        <%# create robots form %>
      <a href="<%= new_robot_path %>" class="btn btn-dark text-white mt-5" style="text-decoration: none;">
        + Add Robot to your Garage
      </a>
    </div>

  </div>
</div>

app/views/pages/home.html.erb
<div class="background-image">
  <div class="container info">
    <h1><strong>RoboRental</strong></h1>
    <h4>Your Source for Whirring Wonders!</h4><br>
    <p>Are you tired of your daily routine?<br>
    Feeling like you need a sidekick with a metallic touch? Look no further!<br>
    RoboRental is here to upgrade your life, one beep at a time.<br>
    Let the adventure with our robots begin! </p>
    <% unless user_signed_in? %>
      <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-light sign-up-button me-4" %>
      <%= link_to "Log In", new_user_session_path, class: "btn btn-light sign-up-button" %>
      <% else %>
      <%= link_to "See our Robots", robots_path, class: "btn btn-light sign-up-button me-4" %>
    <% end %>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="new-booking-container d-flex justify-content-center" data-controller="fake-modal">
  <div class="container m-4 p-4">
    <div class="row align-items-center row justify-content-center font-form">
      <div class="col-lg-7 m-3 p-4 rounded border coloring">
        <div class="d-flex justify-content-between align-items-center">
          <div>
            <h2>Robot specs</h2>
            <p>Model: <%= @robot.model %></p>
            <p>Overview: <%= @robot.overview %></p>
            <p>Price: <%= @robot.price %></p>
            <p>Rating: <%= @robot.rating %></p>
          </div>
          <div>
            <img class="img-properties-form" src="<%= @robot.image_urls.first %>" alt="Robot-picture">
          </div>
        </div>
      </div>



        <div class="col-lg-7 m-3 p-4 rounded border coloring">
          <h2> Leave your review here: </h2>
          <%= render "shared/review_form", booking: @booking, review: @review%>
        </div>
      </div>
    </div>
  </div>

app/views/robots/index.html.erb
<div class="container">

    <div class="row mt-5">

      <% @robots.each do |robot| %>
        <div class="col-4 d-flex mt-5">
          <div class="card mb-4 flex-fill robot-card">
            <img class="card-img-top img-fluid" src="<%= robot.image_urls.first %>">

            <div class="card-body vh-50">
              <h3 class="card-title"><%= robot.model %></h3>
              <p class="card-text"><%= robot.overview %></p>
              <p class="card-text">Price: $<%= number_with_precision(robot.price, precision: 2) %></p>
              <p class="card-text">Rating: <%= robot.rating %></p>
              <%= link_to 'See Robot', robot_path(robot), class: "btn btn-dark w-100 mb-3" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/robots/new.html.erb
<div class="container">
  <div class="layout-form-rb style-activity-form-db">
    <h1 class="mb-4">Add a Robot</h1>
    <%= render "shared/form_robot", robot: @robot %>
  </div>
</div>

app/views/robots/show.html.erb
<div class="show-page-container container p-4 mt-4 mb-4">
  <div class="container d-flex pb-4">
    <div class="container image-container p-0">
      <div class="splide" data-controller="splide">
        <div class="splide__track">
            <!-- Additional required wrapper -->
          <ul class="splide__list">
            <% @robot.image_urls.each do |robot_image| %>
              <li class="splide__slide">
              <img class="w-100" src="<%= robot_image %>">
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="robot-info container" style="padding: 0 50px">
      <h1><%= @robot.model %></h1>
      <p><%= @robot.overview %></p>
        <div class="price-container">
          <h3>$ <%= number_with_precision(@robot.price, precision: 2) %></h3>
          <p><strong>Daily rate </strong></p>
        </div>
          <p><strong>Owner: </strong><%= @robot.user_id %></p>
          <p>Do you want to rent this robot?</p>
          <%= link_to "Rent this bad boy", new_robot_booking_path(@robot), class: "btn btn-dark mb-3" %>
    </div>
  </div>

    <div class="container mt-5">
      <h2>Reviews about <%= @robot.model %></h2>
      <p>Average rating: <%= @robot.rating %></p>
      <% @robot.reviews.each do |review| %>
        <div class="review-card mt-5">
          <p><strong><a href=""><%= review.booking.user.first_name %> <%= review.booking.user.last_name %></strong></a> said:</p>
          <p><%= review.content %><br>
          <em class="review-timestamp">2 days ago</em></p>
        </div>
      <% end %>
      <div class="review-card mt-5">
        <p><strong><a href="https://de.wikipedia.org/wiki/Mustermann">Max Mustermann</strong></a> said:</p>
        <p>Super gud Robot that helps me get into Berghain<br>
        <em class="review-timestamp">2 days ago</em></p>
      </div>
        <div class="review-card">
          <p><strong><a href="https://de.wikipedia.org/wiki/Mustermann">Erika Schmidt</strong></a> said:</p>
          <p>Does backflips and shit! Amazing. Would recommend!!!<br>
          <em class="review-timestamp">2 months ago</em></p>
        </div>
        <div class="review-card">
          <p><strong><a href="https://de.wikipedia.org/wiki/Mustermann">Max Mustermann</strong></a> said:</p>
          <p>Does the dishes, etc. Wird nie µde, schläft nie ein. <br>I sent him to the gym and he didn't gain any weight, which is weird. Doesn't come with a handbook...<br>
          <em class="review-timestamp">9 months ago</em></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_form_booking.html.erb
<%= simple_form_for [ robot, booking ] do |f| %>
  <%= f.input :activity, prompt: "Select...", collection: ["Gardening 🧑‍🌾", "Pet-like buddy 🦮", "Robot Dance Party Extravaganza 🕺", "Hilarious Joke-telling Robot Stand-up 🧑‍🎤"] %>
  <%= f.input :comment, placeholder: "Type something..." %>
  <%= f.submit "Book it now", class: "btn bg-dark text-white", data: {action: "click->fake-modal#activateSuccess"}  %>
<% end %>

app/views/shared/_form_robot.html.erb
<%= simple_form_for(robot) do |f| %>
  <%= f.input :model, placeholder: "Type model..." %>
  <%= f.input :overview, placeholder: "Really good boy..." %>
  <%= f.input :price, placeholder: "Daily rate" %>
  <%= f.submit "Add to my Garage", class: "btn bg-dark text-white" %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar_container fixed-top">
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to robots_path, class: "navbar-brand" do %>
      <%= image_tag "robots_logo.png", style: "padding: 15px" %>
    <% end %>
    <div>
      <h1 class="text-center mb-0 lh-1">RoboRental</h1>
      <h5 class="text-center mb-0 lh-1">Find the best robot for your need</h5>
    </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>



    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
          <li class="nav-item active" >
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item" style="margin-right:25px">
            <%= link_to "Robots", robots_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

            <%= image_tag "https://res.cloudinary.com/wagon/image/upload/c_fill,g_face,h_200,w_200/v1696521230/ovamdokvvff2re3cyxwk.jpg", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", dashboard_path, class: "dropdown-item" %>


              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

</div>

app/views/shared/_review_form.html.erb
<%= simple_form_for [ @booking, @review ] do |f| %>
  <%= f.input :content, placeholder: "Type something..." %>
  <%= f.input :rating, as: :select, collection: (1..5), prompt: "Select a rating", input_html: { class: 'form-control' } %>
  <%= f.submit "Save Review", class: "btn bg-dark text-white", data: {action: "click->fake-modal#activateSuccess"}  %>
<% end %>

app/views/shared/_table_bookings.html.erb
<table class="styled-table mt-4">
    <thead class="border-bottom p-2">
        <tr>
            <th>#id</th>
            <th>Activity</th>
            <th>Content</th>
            <%# <th>Robot model</th> %>
            <th>Booking date</th>
            <th>Review</th>
        </tr>
    </thead>
    <tbody>
      <% user_bookings.each do |b| %>
        <tr class="border-bottom p-2">
            <td><%= b.id %></td>
            <td><%= b.activity %></td>
            <td><%= b.comment %></td>
            <td><%= b.created_at %></td>
            <td>
              <%= link_to "See Booking", booking_path(b) %>
            </td>
        </tr>
      <% end %>
    </tbody>
</table>

app/views/shared/_table_robots.html.erb
<table class="styled-table mt-4">
    <thead class="border-bottom p-2">
        <tr>
            <th>#id</th>
            <th>Model</th>
            <th>Overview</th>
            <%# <th>Robot model</th> %>
            <th>Price</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
      <% user_robots.each do |r| %>
        <tr class="border-bottom p-2">
            <td><%= r.id %></td>
            <td><%= r.model %></td>
            <td><%= r.overview %></td>
            <td><%= r.created_at %></td>
            <td>
              <%= link_to "Delete your robot", dashboard_path %>
            </td>
        </tr>
      <% end %>
    </tbody>
</table>